"""Predefined demo scenarios with scripted dialogue and event steps."""

SCENARIOS: dict[str, dict] = {
    "traffic_stop": {
        "name": "Traffic Stop — Reckless Driver",
        "description": "911 caller reports erratic driving on Highway 281",
        "priority": "P2",
        "incident_type": "traffic",
        "caller_dialogue": [
            "911, what's your emergency?",
            "There's a white Ford F-150 speeding northbound on Highway 281 near Evans Road.",
            "The driver appears intoxicated — swerving across lanes.",
            "No, I don't want to give my name. Just send someone please.",
        ],
        "call_fields": {
            "nature": "Traffic — possible DWI, reckless driver",
            "location": "Highway 281 near Evans Road",
            "cross_streets": "281 / Evans",
            "latitude": 29.518,
            "longitude": -98.452,
            "caller_phone": "210-555-0199",
            "narrative": "White Ford F-150 northbound, erratic driving, possible intoxication",
        },
        "auto_steps": [
            {"delay": 3, "event": "cad_event_created", "actor": "calltaker"},
            {"delay": 5, "event": "unit_assigned", "unit": "1A12", "actor": "dispatcher"},
            {"delay": 4, "event": "officer_enroute", "unit": "1A12", "actor": "officer"},
            {"delay": 6, "event": "officer_onscene", "unit": "1A12", "actor": "officer"},
            {"delay": 3, "event": "report_started", "unit": "1A12", "actor": "officer"},
        ],
    },
    "burglary": {
        "name": "Burglary In Progress",
        "description": "Homeowner reports break-in at residence",
        "priority": "P1",
        "incident_type": "burglary",
        "caller_dialogue": [
            "911, what's your emergency?",
            "Someone is breaking into my neighbor's house! I can hear glass breaking!",
            "1420 Oak Street — the blue house on the corner.",
            "I see a male in a black hoodie near the back door. He might have a weapon.",
        ],
        "call_fields": {
            "nature": "Burglary in progress — suspect on scene",
            "location": "1420 Oak Street",
            "cross_streets": "Oak / 14th",
            "latitude": 29.4261,
            "longitude": -98.4916,
            "weapons_involved": True,
            "caller_name": "Jane Wilson",
            "caller_phone": "210-555-0177",
        },
        "auto_steps": [
            {"delay": 2, "event": "cad_event_created", "actor": "calltaker"},
            {"delay": 3, "event": "incident_escalated", "actor": "supervisor", "note": "P1 escalation — weapons possible"},
            {"delay": 4, "event": "unit_assigned", "unit": "1A12", "actor": "dispatcher"},
            {"delay": 2, "event": "unit_assigned", "unit": "2B07", "actor": "dispatcher"},
            {"delay": 3, "event": "officer_enroute", "unit": "1A12", "actor": "officer"},
            {"delay": 3, "event": "officer_enroute", "unit": "2B07", "actor": "officer"},
            {"delay": 5, "event": "officer_onscene", "unit": "1A12", "actor": "officer"},
            {"delay": 2, "event": "officer_request_backup", "unit": "1A12", "actor": "officer"},
        ],
    },
    "domestic": {
        "name": "Domestic Disturbance",
        "description": "Neighbor reports domestic argument with injuries",
        "priority": "P1",
        "incident_type": "domestic_violence",
        "caller_dialogue": [
            "911, what's your emergency?",
            "My neighbors are fighting — I can hear screaming and things breaking.",
            "8901 Medical Drive, apartment 4B.",
            "I think someone is hurt — I heard a woman crying for help.",
        ],
        "call_fields": {
            "nature": "Domestic disturbance — possible assault",
            "location": "8901 Medical Drive Apt 4B",
            "apartment": "4B",
            "latitude": 29.41,
            "longitude": -98.5,
            "injuries": True,
            "caller_phone": "210-555-0142",
        },
        "auto_steps": [
            {"delay": 2, "event": "cad_event_created", "actor": "calltaker"},
            {"delay": 4, "event": "unit_assigned", "unit": "2B07", "actor": "dispatcher"},
            {"delay": 3, "event": "unit_assigned", "unit": "EMS-3", "actor": "dispatcher"},
            {"delay": 4, "event": "officer_enroute", "unit": "2B07", "actor": "officer"},
            {"delay": 6, "event": "officer_onscene", "unit": "2B07", "actor": "officer"},
        ],
    },
    "officer_assist": {
        "name": "Officer Assistance",
        "description": "Officer activates silent emergency",
        "priority": "P1",
        "incident_type": "officer_emergency",
        "caller_dialogue": [],
        "call_fields": {
            "nature": "OFFICER EMERGENCY — Unit 1A12 silent alarm activated",
            "location": "Last known: Highway 281 / Evans Road",
            "latitude": 29.518,
            "longitude": -98.452,
            "priority": "P1",
        },
        "auto_steps": [
            {"delay": 1, "event": "cad_event_created", "actor": "system"},
            {"delay": 2, "event": "incident_escalated", "actor": "supervisor", "note": "OFFICER EMERGENCY — all available units respond"},
            {"delay": 2, "event": "unit_assigned", "unit": "2B07", "actor": "dispatcher"},
            {"delay": 2, "event": "unit_assigned", "unit": "K9-1", "actor": "dispatcher"},
            {"delay": 3, "event": "officer_enroute", "unit": "2B07", "actor": "officer"},
        ],
    },
    "pursuit": {
        "name": "Vehicle Pursuit",
        "description": "Officer initiates pursuit of fleeing vehicle",
        "priority": "P1",
        "incident_type": "pursuit",
        "caller_dialogue": [],
        "call_fields": {
            "nature": "Vehicle pursuit — white sedan fleeing traffic stop",
            "location": "Highway 281 northbound from Evans Road",
            "latitude": 29.52,
            "longitude": -98.45,
            "priority": "P1",
        },
        "auto_steps": [
            {"delay": 1, "event": "cad_event_created", "actor": "officer"},
            {"delay": 2, "event": "incident_escalated", "actor": "supervisor", "note": "Pursuit authorized — air unit notified"},
            {"delay": 3, "event": "unit_assigned", "unit": "K9-1", "actor": "dispatcher"},
            {"delay": 4, "event": "officer_enroute", "unit": "K9-1", "actor": "officer"},
            {"delay": 5, "event": "supervisor_note_added", "actor": "supervisor", "note": "Monitoring pursuit — spike strip team en route"},
        ],
    },
}
