export const SOCKET_EVENTS = {
  POST_NEW: "post:new",
  COMMENT_NEW: "comment:new",
  REACTION_UPDATE: "reaction:update",
  NOTIFICATION_NEW: "notification:new",
  ALERT_NEW: "alert:new",
  ALERT_UPDATE: "alert:update",
  ALERT_SEVERITY: "alert:severity",
  REPORT_NEW: "report:new",
  REPORT_STATUS: "report:status",
  MAP_MARKER_UPDATE: "map:marker:update",
  LISTING_NEW: "listing:new",
  LISTING_UPDATE: "listing:update",
  LISTING_SOLD: "listing:sold",
  REVIEW_NEW: "review:new",
  INQUIRY_NEW: "inquiry:new",
  BUSINESS_ACTIVITY: "business:activity",
  TASK_ASSIGNED: "task:assigned",
  MODERATION_CASE_NEW: "moderation:case:new",
  MODERATION_CASE_UPDATE: "moderation:case:update",
  BROADCAST_SENT: "broadcast:sent",
  OPS_INCIDENT_UPDATE: "ops:incident:update",
} as const;
